version: 0.2

phases:
  build:
    commands:
      - yarn install
      - aws cloudformation package --template-file template.yml --s3-bucket bc-cicd-demo-$STAGE --output-template-file package.yml
artifacts:
  files:
    - package.yml
