Transform: AWS::Serverless-2016-10-31
Resources:
  ######################
  # Handlers
  ######################
  helloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/helloWorld.handler
      Runtime: nodejs10.x
      CodeUri: .

  helloNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/helloName.handler
      Runtime: nodejs10.x
      CodeUri: .
