Transform: AWS::Serverless-2016-10-31
Parameters:
  Stage:
    Type: String
Resources:
  ######################
  # Handlers
  ######################
  helloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/helloWorld.handler
      Runtime: nodejs10.x
      CodeUri:
        Bucket: !Sub bc-cicd-demo-${Stage}
        Key: 1.0.0.zip

  helloNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/helloName.handler
      Runtime: nodejs10.x
      CodeUri:
        Bucket: !Sub bc-cicd-demo-${Stage}
        Key: 1.0.0.zip
