Transform: AWS::Serverless-2016-10-21
Parameters:
  Stage:
    Type: String
Resources:
  ######################
  # Handlers
  ######################
  helloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/hello-world.handler
      Runtime: nodejs10.x
      CodeUri: !Sub s3://bc-cicd-demo-${Stage}/1.0.0.zip

  helloNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/hello-name.handler
      Runtime: nodejs10.x
      CodeUri: !Sub s3://bc-cicd-demo-${Stage}/v1/1.0.0.zip
