Transform: AWS::Serverless-2016-10-31
Parameters:
  Stage:
    Type: String
Resources:
  ######################
  # Handlers
  ######################
  helloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/helloWorld.handler
      Runtime: nodejs10.x
      CodeUri: src/lambdas/helloWorld.js

  helloNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/helloName.handler
      Runtime: nodejs10.x
      CodeUri: src/lambdas/helloName.js
