Transform: AWS::Serverless-2016-10-21
Parameters:
  Stage:
    Type: String
Resources:
  ######################
  # Handlers
  ######################
  helloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/hello-world.handler
      Runtime: nodejs10.x
      CodeUri:
        FunctionCode:
          Bucket: !Sub bc-cicd-demo-${Stage}
          Key: 1.0.0.zip

  helloNameLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/hello-name.handler
      Runtime: nodejs10.x
      CodeUri:
        FunctionCode:
          Bucket: !Sub bc-cicd-demo-${Stage}
          Key: 1.0.0.zip
